import{a as y,s as L,i as l}from"./assets/vendor-CqsEcRFW.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="45524929-4d44ab8f504de5084895de9cf",w="https://pixabay.com/api/";async function f(r,e=1,s=15){try{return(await y.get(w,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(i){throw console.error("The error is:",i),i}}function m(r){const e=document.querySelector(".gallery");r.forEach(s=>{const i=`
            <li class="image-card">
                <a href="${s.largeImageURL}">
                    <img src="${s.webformatURL}" alt="${s.tags}" />
                    <div class="info">
                        <p><span class="text-span">Likes</span> ${s.likes}</p>
                        <p><span class="text-span">Views</span> ${s.views}</p>
                        <p><span class="text-span">Comments</span> ${s.comments}</p>
                        <p><span class="text-span">Downloads</span> ${s.downloads}</p>
                    </div>
                </a>
            </li>`;e.insertAdjacentHTML("beforeend",i)})}function b(){const r=document.querySelector(".gallery");r.innerHTML=""}const q=document.querySelector(".input-text"),n=document.querySelector(".loader"),E=document.querySelector(".search-form"),a=document.querySelector(".load-more");let g=new L(".gallery a"),d="",c=1;const p=15;let u=0;E.addEventListener("submit",async r=>{if(r.preventDefault(),d=q.value.trim(),c=1,d===""){l.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}n.classList.remove("is-hidden"),a.classList.add("is-hidden"),b();try{const e=await f(d,c,p);n.classList.add("is-hidden"),e.hits.length===0?l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(u=e.totalHits,m(e.hits),g.refresh(),c*p<u&&a.classList.remove("is-hidden"))}catch(e){n.classList.add("is-hidden"),l.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error("The error is:",e)}});a.addEventListener("click",async()=>{c+=1,n.classList.remove("is-hidden"),a.classList.add("is-hidden");try{const r=await f(d,c,p);n.classList.add("is-hidden"),m(r.hits),g.refresh();const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),c*p>=u?(a.classList.add("is-hidden"),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):a.classList.remove("is-hidden")}catch(r){n.classList.add("is-hidden"),l.error({title:"Error",message:"An error occurred while fetching more images. Please try again later.",position:"topRight"}),console.error("The error is:",r)}});
//# sourceMappingURL=index.js.map
